language: node_js

node_js:
  - 'stable'
  - '8'

sudo: false

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

branches:
  only:
  - master

cache:
  directories:
    - node_modules